### ISSUE TITLE
Script is throwing FileNotFoundError on Windows

### ISSUE THREAD

**Issue by acolombo11** [tomchen/font-template#2] opened 2020-08-18 22:12 UTC
While running the py script on Windows 10 w/ the FF bundled distribution of Python, I get the following error:

```
Traceback (most recent call last):
  File "batch_import_svg.py", line 15, in <module>
    glyph.importOutlines(str(p))
FileNotFoundError: [Errno 2] No such file or directory: 'SVG\\305 .svg'
```

I'm working with SVGS exported from the font_template.ai.
I'm not exporting all of the characters, so I'm not exactly sure where's the turning point, but it seems like the script fails for every single file somewhere after character 248 and before character 305, probably because of the way the files are named on Windows. Tomorrow I'll double check if the scripts runs correctly on macOS with the same files.

BTW thanks for the tutorial, the files and the script. Awesome job!

**Comment by tomchen** [comment] 2020-08-19 14:11
I can't reproduce the exact problem you have encounted, but I did find some Unicode filename related problem, which is described in #3 , and which has just been fixed by changing artboard names in `.ai` (and subsequently SVG glyph file names), e.g. `305 ı.svg` is now `305 dotlessi.svg`. Please follow the ["Update your font_template.ai before 2020-08-19" section in the tutorial](https://github.com/tomchen/font-template#update-your-font_templateai-before-2020-08-19), then tell me if you still have the error.

**Comment by acolombo11** [comment] 2020-08-19 16:51
> 
> 
> I can't reproduce the exact problem you have encounted, but I did find some Unicode filename related problem, which is described in #3 , and which has just been fixed by changing artboard names in `.ai` (and subsequently SVG glyph file names), e.g. `305 ı.svg` is now `305 dotlessi.svg`. Please follow the ["Update your font_template.ai before 2020-08-19" section in the tutorial](https://github.com/tomchen/font-template#update-your-font_templateai-before-2020-08-19), then tell me if you still have the error.

The new template worked, thanks a lot!

To transition to I didn't use the js script, I just copied and pasted everything in the new template 🤷

**Comment by tomchen** [comment] 2020-08-19 20:37
Yeah I can imagine a simple copy-paste should do the same job (if those guideline, border, glyph name layers are kept locked and not copied)

**Closed as completed** 2020-08-20 20:01 UTC
